config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin_area', as: 'rails_admin'
  root 'events#index'
  devise_for :admins
  devise_for :photographers, controllers: {passwords:'photographers/passwords' }
  resources :photographers, only: :show do
    get :profile
    post :upd, on: :collection
    get '/', to: 'events#index', as: :events
  end
  resources :events, except: [:index] do
    resources :photos, only: [:index, :create, :update] do
      get :find_faces, :processed, :toggle_tag
    end
    resources :invites, except: [:edit, :update, :new]
    resources :guest_invites, except: [:edit, :update, :new] do
      get :share
      post :upload_csv, on: :collection
    end
    resources :upload_logs, only: [:create, :update]
    resources :error_logs, only: :create
    post :delete_photos, :add_backgrounds, :share, :add_tag, :publish
    get :post_service, :photo_dup, :set_backgrounds
    # post '' => 'events#show'
  end
end

app/models/guest_invite.rb
class GuestInvite < ActiveRecord::Base
  has_one :photographer, through: :event
  belongs_to :event
  enum status: [:not_sent, :sent, :received]
  validate :presence_any
  validates :phone, format: {with: /\A(\d|\+|\-|\.|\s)*\z/}
  validates :email, presence: false, email: true, :if => :test
  before_create :set_code

  def test
    email.present?
  end

  def get_normal_phone
    norm = phone.gsub(/[^\d]/,'')
    if (9..12).include? norm.length
      '+972'.first(13-norm.length)+norm
    end
  end

  def share(url)
    sent!
    InviteMailer.share_event(self, email).deliver_now if email
    if phone && Rails.env=="production"
      @client = Twilio::REST::Client.new Twilio_account, Twilio_auth
      body = event.share_message.gsub('${link}', url)
      @client.account.messages.create({from: '+972526284473', to: get_normal_phone, body: body})
    end
  end

  private
  def presence_any
    errors.add(:email, " and phone can't be blank") if email.blank? && phone.blank?
  end

  def set_code 
    self.code=SecureRandom.uuid
  end
end

app/controllers/guest_invites_controller.rb
class GuestInvitesController < ApplicationController
  before_action :find_event, except: :show
  skip_before_action :authenticate_any!, only: :show 

  def index
    @photographer = @event.photographer
    @guest_invites = @event.guest_invites
  end

  def create
    @guest_invite = @event.guest_invites.new(guest_invite_params)
    if @guest_invite.save
      flash[:notice] = "created invite"
    else
      flash[:alert] = @guest_invite.errors.first.join(' ')
    end
    redirect_to event_guest_invites_path(@event)
  end

  def share
    @guest_invite = @event.guest_invites.find(params[:guest_invite_id])
    @guest_invite.share(event_guest_invite_url(@event.id,@guest_invite.code))
    flash[:notice] = "invite sent"
    redirect_to event_guest_invites_path(@event)
  end

  def destroy
    @event.guest_invites.find(params[:id]).destroy
    flash[:notice] = "invite deleted"
    redirect_to event_guest_invites_path(@event)
  end

  def upload_csv
    file = open(params[:file])
    ext = File.extname(file)
    rows = []
    if ext=='.xls' || ext=='.xlsx'
      spreadsheet = ext=='.xls' ? Roo::Excel.new(file) : Roo::Excelx.new(file)
      header = spreadsheet.row(1)
      for i in 2..spreadsheet.last_row do
        r = Hash[[header, spreadsheet.row(i)].transpose].slice("email", "phone")
        r['phone'] = r['phone'].to_i if r['phone'].class==Float
        rows << r
      end
    else
      CSV.foreach(open params[:file]) do |row|
        row.delete(nil)
        row.each do |r|
          if r=~/\A(\d|\+|\-|\.|\s)*\z/
            rows << {phone: r}
          else
            rows << {email: r}
          end
        end
      end
    end
    rows.each do |row|
      @event.guest_invites.create(row)
    end
    flash[:notice] = "invites added"
    redirect_to event_guest_invites_path(@event)
  end

  def show
    @base_uri = ENV['STAGING_MAIN_SERVER_URL'] || Rails.application.secrets[:env]['MAIN_SERVER_URL']
    @event = Event.find(params[:event_id])
    @guest_invite = @event.guest_invites.find_by_code(params[:id])
    if @guest_invite
      @guest_invite.received!
      redirect_to base_uri+event_path(@event)
    else
      redirect_to base_uri
    end
  end

  private 
  def guest_invite_params
    params.require(:guest_invite).permit(:email,:phone)
  end
end

app/views/guest_invites/_guest_invite.html.erb
<tr>
  <td>
     <%= guest_invite.id %>
  </td>
  <td>
    <%= guest_invite.email %>
  </td>
  <td>
    <%= guest_invite.phone %>
  </td>
  <td>
    <span class="label label-sm label-<%= guest_invite.code ? 'warning' : 'success' %>">
    <%= guest_invite.status %> </span>
  </td>
  <td>
    <%= link_to 'Share',  event_guest_invite_share_path(@event,guest_invite) %>, 
    <%= link_to 'Remove', event_guest_invite_path(@event,guest_invite), method: :delete, 'data-confirm' => "Are you sure?" %>
  </td>
</tr>

app/views/guest_invites/index.html.erb
<% content_for :sidebar do %>
  <%= render 'shared/sidebar' %>
<% end %>
<div class="row">
  <div class="col-md-12">
    <br>
    <h1>Guest invites</h1>
    <%= form_for @event do |f| %>
      <%= f.text_area :share_message %>
      <br>
      <%= f.submit 'Update message' %>
    <% end %>
    <br>
    <%= form_for [@event, GuestInvite.new] do |i| %>
      <%= i.text_field :email, placeholder: 'email' %>
      <%= i.text_field :phone, placeholder: 'phone' %>
      <%= i.submit 'Create event' %>
    <% end %>
    <br>
    <%= form_tag upload_csv_event_guest_invites_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag 'upload file' %>
    <% end %>
    <br>
    <% if @guest_invites.present? %>
      <div class="portlet box red">
        <div class="portlet-title">
          <div class="caption">
            <i class="fa fa-cogs"></i>Invite Guest Table
          </div>
          <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
          </div>
        </div>
        <div class="portlet-body">
          <div class="table-scrollable">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>
                     #
                  </th>
                  <th>
                     Email
                  </th>
                  <th>
                     Phone
                  </th>
                  <th>
                     Status
                  </th>
                  <th>
                     Action
                  </th>
                </tr>
              </thead>
              <tbody>
                <%= render @guest_invites %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>