config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin_area', as: 'rails_admin'
  root 'events#index'
  devise_for :admins
  devise_for :photographers, controllers: {passwords:'photographers/passwords' }
  resources :photographers, only: :show do
    get :profile
    post :upd, on: :collection
    get '/', to: 'events#index', as: :events
  end
  resources :events, except: [:index] do
    resources :photos, only: [:index, :create, :update] do
      get :find_faces, :processed, :toggle_tag
    end
    resources :invites, except: [:edit, :update, :new]
    resources :guest_invites, except: [:edit, :update, :new] do
      get :share
      post :upload_csv, on: :collection
    end
    resources :upload_logs, only: [:create, :update]
    resources :error_logs, only: :create
    post :delete_photos, :add_backgrounds, :share, :add_tag, :publish
    get :post_service, :photo_dup, :set_backgrounds
    # post '' => 'events#show'
  end
end

app/views/shared/_footer.html.haml
/ BEGIN FOOTER
.page-footer
  .page-footer-inner
    2015 © Selffer.
  .scroll-to-top
    %i.icon-arrow-up
/ END FOOTER

app/views/shared/_header.html.haml
/ BEGIN HEADER
.page-header.navbar.navbar-fixed-top
  / BEGIN HEADER INNER
  .page-header-inner
    / BEGIN LOGO
    .page-logo
      %a{href: photographer_path(@photographer)}
        = image_tag asset_path('logo-selffer-white.svg'), alt: 'logo', class: 'logo-default', style: 'height: 30px;'
      .menu-toggler.sidebar-toggler{style: 'display: none'}
        / DOC: Remove the above "hide" to enable the sidebar toggler button on header
    / END LOGO
    / BEGIN PAGE TOP
    .page-top
      / BEGIN TOP NAVIGATION MENU
      .top-menu
        %ul.nav.navbar-nav.pull-right
          - if admin_signed_in? && @event
            -unless @event.id.nil?
              %li
                .actions#process-event
                  = link_to 'Clear Event Cache', event_post_service_path(@event), class: "btn btn-sm green-jungle"
          %li.dropdown.dropdown-user.dropdown-dark
            %a.dropdown-toggle{"data-close-others" => "true", "data-hover" => "dropdown", "data-toggle" => "dropdown", :href => "javascript:;"}
              %span.username.username-hide-on-mobile
                = @photographer.name
              / DOC: Do not remove below empty space( ) as its purposely used
              = image_tag @photographer.logo.url || 'No_image_available.jpg'
              %i.fa.fa-angle-down
            %ul.dropdown-menu.dropdown-menu-default
              - unless @photographer.is_owner
                %li
                  = link_to photographer_profile_path(@photographer) do
                    %i.icon-user
                    My Profile
              %li
                = link_to photographer_events_path(@photographer) do
                  %i.icon-calendar
                  My Events
              %li.divider
              %li
                = link_to destroy_photographer_session_path, method: :delete do
                  %i.icon-key
                  Log Out
          / END USER LOGIN DROPDOWN
      / END TOP NAVIGATION MENU
    / END PAGE TOP
  / END HEADER INNER
/ END HEADER

app/views/shared/_sidebar.html.haml
/ BEGIN SIDEBAR
.page-sidebar-wrapper
  / DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing
  / DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed
  .page-sidebar
    / BEGIN SIDEBAR MENU
    / DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders)
    / DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode
    / DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode
    / DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing
    / DOC: Set data-keep-expand="true" to keep the submenues expanded
    / DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed
    %ul.page-sidebar-menu
      %li.start
        = link_to 'javascript:;', id: 'edit-btn', data: {target: "#edit-event", toggle: "modal"} do
          %i.fa.fa-edit
          %span.title Edit
      %li.start#li-publish
        = link_to 'javascript:;', id: 'publish-btn', data: {target: "#publish-event", toggle: "modal"} do
          %i.fa.fa-bullhorn
          %span.title Publish
      %li.start#li-preview
        = link_to (@base_uri+event_path(@event)), id: 'preview-btn', toggle: "modal", target: "_blank" do
          %i.fa.fa-eye
          %span.title Preview
      %li.start#li-invite
        = link_to 'javascript:;', id: 'publish-btn', data: {target: "#publish-event", toggle: "modal"} do
          %i.fa.fa-user-plus
          %span.title Invite
      %li.start#published
        = link_to (@base_uri+event_path(@event)), id: 'publish-btn', toggle: "modal", target: "_blank" do
          %i.fa.fa-eye
          %span.title View

-if !@event.is_published && @photos.present?
  :javascript
    $(function(){
      $('#li-preview, #li-publish').css('display', 'inline-block');
    })
-elsif !@event.is_published && !@photos.present?
  :javascript
    $(function(){
      $('#li-preview').css('display', 'inline-block');
    })
-elsif @event.is_published
  :javascript
    $(function(){
      $('#li-invite').css('display', 'inline-block');
      $('#published').css('display', 'inline-block');
    })

:javascript
  $(function(){
    $("#preview-btn").click(function(e){
      var win = window.open('');
      $.get("/events/#{@event.id}/set_backgrounds.json",
        function(data){
          if(data){
            $('#bg_photo_count').text(data.covers_count);
            win.location = "#{@base_uri + event_path(@event)}";
          }
        })
      return false;
    })
  })