config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin_area', as: 'rails_admin'
  root 'events#index'
  devise_for :admins
  devise_for :photographers, controllers: {passwords:'photographers/passwords' }
  resources :photographers, only: :show do
    get :profile
    post :upd, on: :collection
    get '/', to: 'events#index', as: :events
  end
  resources :events, except: [:index] do
    resources :photos, only: [:index, :create, :update] do
      get :find_faces, :processed, :toggle_tag
    end
    resources :invites, except: [:edit, :update, :new]
    resources :guest_invites, except: [:edit, :update, :new] do
      get :share
      post :upload_csv, on: :collection
    end
    resources :upload_logs, only: [:create, :update]
    resources :error_logs, only: :create
    post :delete_photos, :add_backgrounds, :share, :add_tag, :publish
    get :post_service, :photo_dup, :set_backgrounds
    # post '' => 'events#show'
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders, :history]
  acts_as_taggable

  belongs_to :photographer
  belongs_to :watermark_portrait, class_name: "Watermark"
  belongs_to :watermark_landscape, class_name: "Watermark"
  has_many :photos, dependent: :destroy
  has_many :event_translations, dependent: :destroy
  has_many :invites, dependent: :destroy
  has_many :users, through: :invites, foreign_key: :event_id
  has_many :guest_invites, dependent: :destroy
  has_many :upload_logs, dependent: :destroy
  has_many :archives, dependent: :destroy
  # scope :empty, ->{ where(name: nil, date: nil, photos_count: nil, guests: nil) }
  scope :not_empty, ->{ where.not('name is null and date is null and photos_count is null and guests is null') }
  scope :not_deleted, ->{where.not(status: 1)}
  after_save :name_translate_change, if: :name_changed?
  before_update :set_default_name_and_date, if: :name_or_date_blank?
  before_update :service_new_event
  before_save :encrypt_password, if: :password_changed?
  before_save :check_password, if: :password_changed?

  enum status: [:normal, :deleted]

  HEADERS = { 'Content-Type' => 'application/json; charset=UTF-8', 'Accept' => 'application/json' }

  def background_or_photo
    self.photos.order(background: :desc).first_or_initialize
  end

  def decorate_date
    date.strftime('%d.%m.%Y') if date
  end

  def slug_candidates
    [[:name, :pretty_date]]
  end

  def pretty_date
    date ? date.strftime("%e-%m-%y").strip : ''
  end

  def should_generate_new_friendly_id?
    new_record? || ((name_changed? ||  date_changed? || id_changed?) && self.name.present? && self.date.present?) || super
  end

  def get_translated(field, lang)
    event_translations.find_by_lang(lang).try(field)
  end

  def long_id
    length_id = 6-self.id.to_s.size
    length_id<0 ? self.id : '0'*length_id+self.id.to_s
  end

  def photo_slug
    "#{long_id}#{self.slugs.order(:created_at).last.slug[6..-1]}"
  end

  def default_message
    "The photos from #{name} from #{date.strftime("%B %d %Y")} are ready! Press here to see your photos ${link}"
  end

  def share_message
    super || default_message
  end

  def encrypt_password
    unless password.nil?
      self.password = Base64.encode64(self.password)
    end
  end

  def check_password
    if self.password == nil && Event.find(self.id).password !=nil
      self.password = Event.find(self.id).password
    end
  end

  def name_or_date_blank?
    self.name.blank? || self.date.blank?
  end

  def name_for_service
    en_name = event_translations.find_or_create_by(lang: 'en').name.presence
    he_name = event_translations.find_or_create_by(lang: 'he').name.presence
    en_name || he_name || name
  end


  private

  def name_translate_change
    e_tr = self.event_translations.find_or_create_by(lang: 'en') do |e_t|
      e_t.name = self.name
    end
    e_tr.update(name: self.name) if e_tr.name!=self.name
  end

  def service_new_event
    if name_changed?(from: nil)
      url = ApiUrlHelper.api_url_eb "/event/new"
      body = {'EventSlug' => self.slugs.order(:created_at).last.slug,
              'EventName' => name, # use translations - name_for_service
              'NeedsModeration' => needs_moderation,
              'AllowNotifications' => false}.to_json
      @response = HTTParty.post(url, headers: HEADERS, body: body)
      @response.code/100==2 && @response['Success']
      self.id = @response["EventId"]
      self.slugs.each do |f| f.update_attribute(:sluggable_id, self.id) end
    else
      url = ApiUrlHelper.api_url_eb "/event/#{self.id}"
      body = {'EventName' => name, # use translations - name_for_service
              'NeedsModeration' => needs_moderation,
              'AllowNotifications' => send_notification}.to_json
      @response = HTTParty.put(url, headers: HEADERS, body: body)
      @response.code/100==2 && @response['Success']
    end
  rescue
    return false
  end

  def set_default_name_and_date
    self.slug = nil
    if self.name.blank?
      default_name = "event no name"
      self.name = default_name
      while Event.find_by_name self.name
        event_number = event_number ? event_number+1 : 2
        self.name = "#{default_name} #{event_number}"
      end
    end
    self.date = Time.now if self.date.blank?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, except: [:index, :create]
  before_action :find_photographer, except: :photo_dup
  before_action :normal_url, except: [:update, :destroy]
  before_action :photo_ids, only: [:delete_photos, :add_backgrounds]

  HEADERS = { 'Content-Type' => 'application/json; charset=UTF-8', 'Accept' => 'application/json' }

  def index
    @event = Event.new
    @events = @photographer.events.where.not(status: 1).not_empty.order(created_at: :desc)
    @events_shared = @photographer.shared_events.not_deleted.order(created_at: :desc)
    # @new_event = @photographer.events.empty.first_or_create
  end

  def edit
  end

  def create
    @event = @photographer.events.create
    @event.assign_attributes(event_params)
    respond_to do |f|
      if @event.save!
        status = 202
        f.html{redirect_to event_path(@event)}
      else
        status ||= 422
      end
    end
    translations = params[:event].delete(:lang)
    if translations
      translations.each do |k,v|
        @et = @event.event_translations.find_or_create_by(lang: k)
        @et.update event_translation_params(v)
      end
    end
  end

  def update
    translations = params[:event].delete(:lang)
    if translations
      translations.each do |k,v|
        @et = @event.event_translations.find_or_create_by(lang: k)
        @et.update event_translation_params(v)
      end
    end
    @event.restore_attributes
    @event.assign_attributes(event_params)
    respond_to do |f|
    if @event.save!
      # flash[:notice] = "Event successfully updated"
      status = 202
      f.html { redirect_to event_path(@event) }
      f.json { respond_with_bip(@event) }
      f.js {}
    else
      # flash[:alert] = "Service not available. try again later"
      status ||= 422
    end
   end
    @event.save unless @event.slug
    # respond_to do |f|
    #   f.html { redirect_to event_path(@event) }
    #   f.json { render nothing: true, status: status }
    #   f.json { respond_with_bip(@event) }
    #   f.js {}

  end

  def show
    gon.restrictFolderDrag =  t "photographer_client.drag_folder_restrict"
    @base_uri = ENV['STAGING_MAIN_SERVER_URL'] || Rails.application.secrets[:env]['MAIN_SERVER_URL']
    gon.event_id = @event.id.to_s
    gon.is_photographer = photographer_signed_in? && !admin_signed_in?
    # Rails.logger.warn("Look at me, I'm a warning")
    @sort = params[:sort] || 'asc'
    @type = params[:type]
    @types = ['backgrounds', 'album', 'like', 'priv', 'not_priv']
    @photos = @event.photos.processed.is_show.includes(:tags)
    # @photos.each do |photo|
    #   link = photo.img
    #   name = link.split('/').last
    #   encoded_name =  ERB::Util.url_encode(URI.decode(name))
    #   url = link.gsub(name, encoded_name)
    #   photo.update_attribute(:img, url)
    # end
    @tag = params[:tag].presence
    @tags = @event.tag_list
    @tags_count = @tags.flat_map{|t| [t, @photos.tagged_with(t).count]}
    @tags_count = Hash[*@tags_count]
    @process_count = @event.photos.not_processed.count
    @photos = @photos.order(time_stamp: @sort)
    gon.backgrounds = @photos.backgrounds.pluck(:id)
    @all_count = @photos.count
    @bg_count = @photos.backgrounds.count
    @album_count = @photos.albums.count
    @like_count = @photos.likes.count
    @priv_count = @photos.privs.count
    # @photo_ids = @photos.page(1).pluck(:id)
    # @photo_ids += @photos.backgrounds.page(1).pluck(:id)
    # @photo_ids += @photos.albums.page(1).pluck(:id)
    # @photo_ids += @photos.likes.page(1).pluck(:id)
    # @photo_ids += @photos.privs.page(1).pluck(:id)
    # @photos = @photos.find(@photo_ids.uniq)
    @photos = get_photos(params[:type]).processed.is_show.includes(:tags)
    @photos = @photos.tagged_with(URI.decode(@tag)) if @tag
    @photos = @photos.order(time_stamp: @sort).page(1)
    @invites = @event.invites
  end

  def destroy
    @event.deleted!
    flash[:alert] = "Event deleted"
    redirect_to photographer_events_path(@photographer)
  end

  def delete_photos
    @all_photos = @event.photos.processed
    @all_count = @all_photos.count
    @bg_count = @all_photos.backgrounds.count
    @priv_count = @all_photos.privs.count
    @not_priv_count = @all_count - @priv_count
    @like_count = @all_photos.likes.count
    @album_count = @all_photos.albums.count
    @photos = get_photos(params[:type]).where(id: @photo_ids).destroy_all
    @photo_ids.each do |photo_id|
      url = ApiUrlHelper.api_url_eb "/event/#{@event.id}/photo/#{photo_id}?isthirdpartyphotoid=1"
      HTTParty.delete(url, headers: headers)
    end
    @amount = @photos.count
  end

  def add_backgrounds
    @photos = get_photos(params[:type]).processed
    new_not_bg = @photos.processed.backgrounds.where.not(id: @photo_ids)
    new_bg = @photos.where.not(background: true).where(id: @photo_ids)
    @changed_photo_ids = new_not_bg.pluck(:id)+new_bg.pluck(:id)
    @changed_photos = @event.photos.processed.where(id: @changed_photo_ids)
    new_not_bg.update_all(background: false)
    new_bg.update_all(background: true)
    # PhotosSyncWorker.perform_async(@changed_photo_ids) unless Rails.env=="development"
    @photos = @photos.where(id: @photo_ids)
    @amount = @photos.count
  end

  def post_service
    if admin_signed_in?
      url = ApiUrlHelper.api_url "/faceush/api/match.svc/cacheevent"
      body = {EventId: @event.id, UserId: @event.photographer.id, IsReload: true }.to_json
      response = HTTParty.post(url, headers: HEADERS, body: body)
      flash[:notice] = response["IsError"]==false ? "Event cache cleared" : "Error: #{response["ErrorMessage"]}"
    else
      flash[:alert] = 'You are not admin!'
    end
    redirect_to event_path(@event)
  end

  # def publish
  #   published = false
  #   unless @event.is_published
  #     @event.update(is_published: true)
  #     published = true
  #   end
  #   render 'events/publish', locals: {published: published}
  # end

  def photo_dup
    begin
      Rails.logger.info "checking dupllicate: #{params[:name]}"
      @photo = @event.photos.find_by(original_filename: params[:name], time_stamp: params[:date])
      respond_to do |f|
        f.json {render json: @photo.present?}
      end
    rescue => e
      Rails.logger.error { "error checking duplicate: #{handle}, #{e.message} #{e.backtrace.join("\n")}" }
    end
  end

  def add_tag
    @tag = params[:tag]
    exist_tag = @event.tag_list.include?(@tag)
    unless exist_tag
      @event.tag_list.add(@tag)
      @count = @event.photos.tagged_with(@tag).count
      @event.save
    end
  end

  def set_backgrounds
    photos = @event.photos.processed
    unless photos.backgrounds.blank?
      render json: true, status: "200"
      return
    end
    url = ApiUrlHelper.api_url_eb "/event/#{params[:event_id]}?additionalfields=cover_photos"
    response = HTTParty.get(url, headers: { 'Content-Type' => 'application/json; charset=UTF-8', 'Accept' => 'application/json' })
    if response.code/100 == 2
      urls = response['CoverPhotos'].map{|p| "%#{p['Url']}%"}
      photos.where("img ILIKE ANY ( array[?] )", urls).update_all(background: true)
      render json: {covers_count: photos.backgrounds.count}, status: "200"
    else
      render json: false, status: "500"
    end
  end

  private

  def event_params
    params[:event][:date] = Date.strptime(params[:event][:date], "%d.%m.%Y") if params[:event][:date].present?
    params.require(:event).permit(:name, :date, :event_type, :description, :guests, :share_message)
  end

  def event_translation_params(hsh)
    hsh.permit(:name,:description,:event_type,:place)
  end

  def event_id
    super || params[:id]
  end

  def normal_url
    if request.path != url_for(only_path: true)
      redirect_to url_for, status: :moved_permanently
    end
  end

  def photo_ids
    @photo_ids = params[:photos_hidden].split(',').map(&:to_i)
    if params[:exclude]=='true'
      @photo_ids = @event.photos.pluck(:id)-@photo_ids
    end
  end
end

app/views/events/_event.html.erb
<div class="col-md-3 col-sm-4 mix category_2 photo not_square_resized">
  <%= link_to event_path(event) do %>
    <div class="mix-inner">
      <%= image_tag event.background_or_photo.img_url_low || 'No_image_available.jpg', class: "img-responsive", alt: '' %>
      <div class="mix-details photo-phrame">
        <h4><%= event.name %> (<%= event.decorate_date %>)</h4>
      </div>
    </div>
  <% end %>
</div>

app/views/events/_event_modal.html.erb
<div id="edit-event" class="modal container fade" tabindex="-1">
  <div class="modal-body" id = 'modal'>
    <div class="portlet light">
      <div class="portlet-title">
        <div class="caption font-red-sunglo">
          <span class="caption-subject bold uppercase"> Event </span>
        </div>
      </div>
      <div class="portlet-body form">
        <%= form_for @event, role: "form", remote: @event.id.present? do |f| %>
          <div class="form-body">
            <div class="form-group form-md-line-input">
              <%= f.text_field :name, id: "form_control_name", class: "form-control lang-fields en-fields", placeholder: "Enter event name"  %>

              <label for="form_control_name">Event name</label>

              <span class="help-block">Write event owner name, for Example: Dana&David</span>
              <span class="error" id = 'required' hidden> <%= t "photographer_client.event_name_required"%> </span>
            </div>
            <%= image_tag("http://i.imgur.com/6RMhx.gif", id: "loading-indicator-event", hidden: true) %>
            <div class="form-group form-md-line-input">
              <%= f.text_field :event_type, id: "form_control_1", class: "form-control lang-fields en-fields", placeholder: "Enter event type"  %>
              <label for="form_control_1">Event type</label>
              <span class="help-block">Write the event type, for Example: Wedding</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_field :date, value: @event.decorate_date, class: "form-control form-control-inline date-picker", placeholder: "Enter event date", size: 16, data: {"date-format" => "dd.mm.yyyy"}  %>
              <label for="form_control_1">Event date</label>
              <span class="help-block">Select date</span>
            </div>
            <% if admin_signed_in? %>
                <%= hidden_field_tag "photographer_id", @photographer.id %>
            <% end %>
            <!-- <div class="form-group form-md-line-input">
              <%= f.text_field :guests, class: "form-control", placeholder: "Enter guests amount"  %>
              <label for="form_control_1">Event guests amount</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_field :place, class: "form-control lang-fields en-fields", placeholder: "Enter event place"  %>
              <label for="form_control_1">Event place</label>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_area :description, class: "form-control lang-fields en-fields", placeholder: "Enter description", rows: 4  %>
              <label for="form_control_1">Description</label>
            </div> -->
          </div>
          <!-- <h4><%# link_to 'preview your event page', "#{ENV['STAGING_MAIN_SERVER_URL'] || Rails.application.secrets[:env]['MAIN_SERVER_URL']}/events/#{@event.slug}", target: '_blank' %></h4> -->
          <div class="form-actions noborder">
            <%= f.submit 'Submit', class: "btn blue", id: 'btn-blue'%>
            <a data-dismiss="modal" class="btn btn-default cancel-btn">Cancel</a>
          </div>
        <%end%>
<!--         <h2>Cover photos</h2><p>You can change it in <%#= link_to "gallery", event_path(@event) %></p>
        <div class="row mix-grid" id='photo-gallery'>
          <%# render @bg_photos %>
        </div> -->
      </div>
    </div>
  </div>
</div>
<script>
$(function(){
  $('#btn-blue').on('click', function(e){
    if ($('#form_control_name').val() == ''){
      e.preventDefault();
        $('#required').fadeIn('slow');
        $('#form_control_name').val('');
        $('#form_control_name').focus(function() {
        $('#required').hide();
        $('#form_control_name').val('');
        });
    } else {
        $('#loading-indicator-event').show();
    }
  });
});
</script>

app/views/events/add_backgrounds.js.erb
toastr.success('<%= @amount %> photos selected as cover photos');
$('#bg_photo_count').text('<%= @amount %>');
gon.backgrounds = <%= @photos.pluck(:id) %>
<% @changed_photos.each do |photo| %>
  var bg_photo = $('#photo-<%=photo.id%>');
  <% if photo.background %>
    bg_photo.removeClass('category_2')
    bg_photo.addClass('category_1')
  <% else %>
    bg_photo.removeClass('category_1')
    bg_photo.addClass('category_2')
  <% end %>
<% end %>

app/views/events/add_tag.js.erb
$('#tag_li').before('<li> <%= link_to change_tag_if_hebrew(@tag, @count), event_path(@event, tag: URI.encode(@tag)), data: {tag: "tag"} %> </li>')
<% @event.photos.each do |photo| -%>
$("#photo-<%=photo.id%>-tags").append('<li> <%= link_to(@tag, event_photo_toggle_tag_path(@event, photo, tag: URI.encode(@tag)), class: "photo-tag", remote: true )%> </li>');
<% end -%>
$('#tag_form #tag').val('');

app/views/events/delete_photos.js.erb
toastr.success('<%= @amount %> photos removed');
<% @photos.each do |photo| %>
  $('#photo-<%=photo.id%>').remove();
<% end %>
$('#all_photo_count').text('<%= @all_count %>');
$('#bg_photo_count').text('<%= @bg_count %>');
$('#priv_photo_count').text('<%= @priv_count %>');
$('#not_priv_photo_count').text('<%= @not_priv_count %>');
$('#like_photo_count').text('<%= @like_count %>');
$('#album_photo_count').text('<%= @album_count %>');
Portfolio.init();

app/views/events/edit.html.erb
<% content_for :sidebar do %>
  <%= render 'shared/sidebar' %>
<% end %>
<% content_for :js do %>
  <%= javascript_include_tag 'jquery.lazyload' %>
  <script>
    $(function(){
      $('.tabs').click(function(){
        $('.lang-fields').hide();
        if(this.id=='en'){
          $('.en-fields').show();
        } else if(this.id=='he'){
          $('.he-fields').show();
        }
      })
      $("img.not-loaded").lazyload({
        effect: 'fadeIn',
        load: function() {
          $(this).removeClass("not-loaded");
          $(this).parent().parent().addClass('not_square_resized')
          square_resize();
        }
      });
    })
  </script>
<% end %>
<ul class="page-breadcrumb breadcrumb">
  <li>
    <%= link_to 'Home', photographer_events_path(@photographer) %>
    <i class="fa fa-circle"></i>
  </li>
  <li>
    <%= link_to @event.name || 'No name', event_path(@event) %>
    <i class="fa fa-circle"></i>
  </li>
  <li>
    <%= link_to 'Edit', edit_event_path(@event) %>
  </li>
</ul>
<!-- BEGIN PAGE CONTENT-->
<div class="row">
  <div class="col-md-12 ">
    <!-- BEGIN SAMPLE FORM PORTLET-->
    <div class="portlet light">
      <div class="portlet-title">
        <div class="caption font-red-sunglo">
          <span class="caption-subject bold uppercase"> Event </span>
        </div>
        <div class="actions">
          <%= link_to 'Delete', event_path(@event), method: :delete, class: "btn btn-sm red", 'data-confirm' => "Are you sure?" %>
        </div>
        <% if admin_signed_in? %>
          <div class="actions" id='process-event'>
            <%= link_to 'Process event', event_post_service_path(@event), class: "btn btn-sm green" %>
          </div>
        <% end %>
      </div>
      <div class="portlet-body form">
        <ul class="nav nav-tabs">
          <li class="active">
            <a href="#portlet_tab3" id="en" class='tabs' data-toggle="tab">
            English </a>
          </li>
          <li>
            <a href="#portlet_tab2" id="he" class='tabs' data-toggle="tab">
            Hebrew </a>
          </li>
        </ul>
        <%= form_for @event, role: "form" do |f| %>
          <div class="form-body">
            <div class="form-group form-md-line-input">
              <%= text_field_tag 'event[lang[en[name]]]', @event.get_translated(:name, 'en'), id: "form_control_1", class: "form-control lang-fields en-fields", placeholder: "Enter event name"  %>
              <%= text_field_tag 'event[lang[he[name]]]', @event.get_translated(:name, 'he'), id: "form_control_1", class: "form-control lang-fields he-fields", placeholder: "Enter event name", style: 'display: none;'  %>
              <label for="form_control_1">Event name</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= text_field_tag 'event[lang[en[event_type]]]', @event.get_translated(:event_type, 'en'), id: "form_control_1", class: "form-control lang-fields en-fields", placeholder: "Enter event type"  %>
              <%= text_field_tag 'event[lang[he[event_type]]]', @event.get_translated(:event_type, 'he'), id: "form_control_1", class: "form-control lang-fields he-fields", placeholder: "Enter event type", style: 'display: none;'  %>
              <label for="form_control_1">Event type</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_field :date, value: @event.decorate_date, class: "form-control form-control-inline date-picker", placeholder: "Enter event date", size: 16  %>
              <label for="form_control_1">Event date</label>
              <span class="help-block">Select date</span>
            </div>
            <!-- <div class="form-group form-md-line-input">
              <%= f.text_field :guests, class: "form-control", placeholder: "Enter guests amount"  %>
              <label for="form_control_1">Event guests amount</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= text_field_tag 'event[lang[en[place]]]', @event.get_translated(:place, 'en'), class: "form-control lang-fields en-fields", placeholder: "Enter event place"  %>
              <%= text_field_tag 'event[lang[he[place]]]', @event.get_translated(:place, 'he'), class: "form-control lang-fields he-fields", placeholder: "Enter event place", style: 'display: none;'  %>
              <label for="form_control_1">Event place</label>
            </div>
            <div class="form-group form-md-line-input">
              <%= text_area_tag 'event[lang[en[description]]]', @event.get_translated(:description, 'en'), class: "form-control lang-fields en-fields", placeholder: "Enter description", rows: 4  %>
              <%= text_area_tag 'event[lang[he[description]]]', @event.get_translated(:description, 'he'), class: "form-control lang-fields he-fields", placeholder: "Enter description", rows: 4, style: 'display: none;'  %>
              <label for="form_control_1">Description</label>
            </div> -->
          </div>
          <!-- <h4><%# link_to 'preview your event page', "#{ENV['STAGING_MAIN_SERVER_URL'] || Rails.application.secrets[:env]['MAIN_SERVER_URL']}/events/#{@event.slug}", target: '_blank' %></h4> -->
          <div class="form-actions noborder">
            <%= f.submit 'Submit', class: "btn blue" %>
          </div>
        <%end%>
<!--         <h2>Cover photos</h2><p>You can change it in <%= link_to "gallery", event_path(@event) %></p>
        <div class="row mix-grid" id='photo-gallery'>
          <%# render @bg_photos %>
        </div> -->
      </div>
    </div>
    <!-- END SAMPLE FORM PORTLET-->
  </div>
</div>

app/views/events/index.html.erb
<% content_for :css do %>
  <link href="/assets/admin/pages/css/portfolio.css" rel="stylesheet" type="text/css"/>
<% end %>
<% content_for :js do %>
  <script src="/assets/admin/pages/scripts/portfolio.js"></script>
<% end %>
<!-- BEGIN PAGE HEADER-->
<!-- BEGIN PAGE HEAD -->
<div class="page-head">
  <!-- BEGIN PAGE TITLE -->
  <div class="page-title">
    <h1>Events</h1>
  </div>
  <!-- END PAGE TITLE -->
</div>
<!-- END PAGE HEAD -->
<!-- BEGIN PAGE BREADCRUMB -->
<ul class="page-breadcrumb breadcrumb">
  <li>
    <%= link_to 'Home', photographer_events_path(@photographer) %>
  </li>
</ul>
<!-- END PAGE BREADCRUMB -->
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
  <div class="col-md-12">
    <div class="tabbable tabbable-custom tabbable-noborder">
      <div class="tab-content">
        <div class="tab-pane active" id="tab_1">
          <!-- BEGIN FILTER -->
          <div class="margin-top-10">
            <div class="row mix-grid" id='photo-gallery'>
              <% unless @photographer.is_owner %>
                <% if @photographer.id > 300 || current_admin.present? %>
                  <div class="col-md-3 col-sm-4 mix category_2 photo">
                    <div class="mix-inner" id='add-new-event'>
                      <div class="mix-details photo-load-area">
                        <%= link_to '', "#", {class: "mix-link center-link", id: 'add-event', data: {toggle: "modal", target: "#edit-event"}}%>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
              <%= render @events %>
              <%= render @events_shared %>
              <%= render 'event_modal' %>
            </div>
          </div>
          <!-- END FILTER -->
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(function(){
    Portfolio.init();
      <% if photographer_signed_in? && !admin_signed_in? %>
      $('#add-event').click(function(){
        // var metadata = {
        //   event_number: <%#=@new_event.id.to_s%>,
        //   event_url: '/events/' + <%#=@new_event.id.to_s%>
        // };
        Intercom('trackEvent', 'new-event-added', metadata);
      });
    <% end %>
});
</script>

app/views/events/publish.js.erb
<% if published %>
    $('.modal.in').modal('hide');
    toastr.success("Event sucsessfully published");
    $('#li-publish').hide();
    $('#li-preview').hide();
    $('#li-invite').css('display', 'inline-block');
    $('#published').css('display', 'inline-block');
    $('#btn-publish').hide();
    $('#close-invite-btn').show();
<% end %>

app/views/events/update.js.erb
window.history.pushState(null, '', '<%= event_path(@event) %>');
$('h1#event-name').html('<%= best_in_place @event, :name, :nil => 'Input event name' %>');
$('h1#event-date').html('<%= best_in_place @event, :date, as: :date, display_as: :decorate_date, value: @event.decorate_date, inner_class: "date-picker" %>');
$('#loading-indicator-event').hide();
$('.best_in_place').click(function(){
  setTimeout(function(){
    $('.date-picker').change(function(){
      $('.date-picker').datepicker('hide');
      $('.form_in_place').submit();
    })
  }, 100);
})