config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin_area', as: 'rails_admin'
  root 'events#index'
  devise_for :admins
  devise_for :photographers, controllers: {passwords:'photographers/passwords' }
  resources :photographers, only: :show do
    get :profile
    post :upd, on: :collection
    get '/', to: 'events#index', as: :events
  end
  resources :events, except: [:index] do
    resources :photos, only: [:index, :create, :update] do
      get :find_faces, :processed, :toggle_tag
    end
    resources :invites, except: [:edit, :update, :new]
    resources :guest_invites, except: [:edit, :update, :new] do
      get :share
      post :upload_csv, on: :collection
    end
    resources :upload_logs, only: [:create, :update]
    resources :error_logs, only: :create
    post :delete_photos, :add_backgrounds, :share, :add_tag, :publish
    get :post_service, :photo_dup, :set_backgrounds
    # post '' => 'events#show'
  end
end

app/models/photographer.rb
class Photographer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  extend FriendlyId
  friendly_id :studio_name, use: [:slugged, :finders]
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
  has_many :invites, dependent: :destroy, through: :events
  has_many :incoming_invites, dependent: :destroy, class_name: Invite, foreign_key: :invited_id
  has_many :shared_events, through: :incoming_invites, source: :event
  has_many :invited, through: :invites
  has_many :inviters, through: :incoming_invites, source: :photographer
  has_many :guest_invites, dependent: :destroy, through: :events
  has_many :watermarks
  mount_uploader :logo, LogoUploader
  after_update :cut_logo, :if => :cropping?
  # after_update :sync_photographer
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h, :crop_rotate

  def cropping?
    crop_x && crop_y && crop_w && crop_h && crop_rotate
  end

  def should_generate_new_friendly_id?
    studio_name_changed? || super
  end

  private
  def sync_photographer
    PhotographerSyncWorker.perform_async(self.id) unless Rails.env=="development"
  end

  def cut_logo
    logo.manipulate! do |img|
      img.rotate crop_rotate
      img.crop "#{crop_w}x#{crop_h}+#{crop_x}+#{crop_y}"
    end
    logo.resize_to_fit(-1, ENV['PHOTOGRAPHER_LOGO_HEIGHT'] || Rails.application.secrets[:env]['PHOTOGRAPHER_LOGO_HEIGHT'])
  end
end

app/controllers/photographers/passwords_controller.rb
class Photographers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/photographers/registrations_controller.rb
class Photographers::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    if accept_invite
      resource.update(is_owner: true)
      photographer_events_path(resource)
    else
      photographer_profile_path(resource)
    end
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/photographers_controller.rb
class PhotographersController < ApplicationController
  before_action :find_photographer

  def profile
    if request.path != url_for(only_path: true)
      redirect_to url_for, status: :moved_permanently
    end
    if current_photographer.try(:is_owner)
      redirect_to photographer_profile_path(current_photographer)
    end
  end

  def upd
    if @photographer.update(photographer_params)
      flash[:notice] = "Your profile successfully updated"
    else
      flash[:alert] = "Service not available. try again later"
    end
    # PhotographerSyncWorker.perform_async(@photographer.id) unless Rails.env=="development"
    redirect_to photographer_profile_path(@photographer)
  end

  private
  def photographer_params
    params.require(:photographer).permit( :name, :studio_name, :street, :zipcode,
                                          :city, :country, :mobile_number, :office_number,
                                          :website, :facebook, :twitter, :instagram, :logo,
                                          :crop_x, :crop_y, :crop_w, :crop_h, :crop_rotate )
  end
end

app/views/photographers/profile.html.erb
<% content_for :js do %>
  <%= javascript_include_tag 'cropper.min' %>
<% end %>
<% content_for :css do %>
  <%= stylesheet_link_tag "cropper.min" %>
<% end %>
<!-- BEGIN PAGE BREADCRUMB -->
<ul class="page-breadcrumb breadcrumb">
  <li>
    <%= link_to 'Home', photographer_events_path(@photographer) %>
    <i class="fa fa-circle"></i>
  </li>
  <li>
    <%= link_to 'Profile', photographer_profile_path(@photographer) %>
  </li>
</ul>
<!-- END PAGE BREADCRUMB -->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
  <div class="col-md-12 ">
    <!-- BEGIN SAMPLE FORM PORTLET-->
    <div class="portlet light">
      <div class="portlet-title">
        <div class="caption font-red-sunglo">
          <span class="caption-subject bold uppercase"> Profile </span>
        </div>
      </div>
      <div class="portlet-body form">
        <%= form_for @photographer, url: upd_photographers_path, method: :post, role: "form" do |f| %>
          <% if admin_signed_in? %>
            <%= f.hidden_field :id %>
          <% end %>
          <div class="form-body">
            <%= image_tag @photographer.logo.url, class: 'full-logo' %>
            <div class="form-group form-md-line-input" id="big-file-input">
              <%= f.file_field :logo, class: "form-control"%>
              <label for="form_control_1">logo</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <a class="btn default" data-target="#full-width" data-toggle="modal" id="width-btn"></a>
            <div class="form-group form-md-line-input">
              <%= f.text_field :name, class: "form-control", placeholder: "Enter name"  %>
              <label for="form_control_1">name</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_field :studio_name, class: "form-control", placeholder: "Enter studio name"  %>
              <label for="form_control_1">Studio name</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_field :street, class: "form-control", placeholder: "Enter street"  %>
              <label for="form_control_1">Street</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_field :zipcode, class: "form-control", placeholder: "Enter zipcode"  %>
              <label for="form_control_1">Zipcode</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_field :city, class: "form-control", placeholder: "Enter city"  %>
              <label for="form_control_1">City</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_field :country, class: "form-control", placeholder: "Enter country"  %>
              <label for="form_control_1">Country</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_field :mobile_number, class: "form-control", placeholder: "Enter mobile number"  %>
              <label for="form_control_1">Mobile number</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_field :office_number, class: "form-control", placeholder: "Enter mobile number"  %>
              <label for="form_control_1">Office number</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_field :website, class: "form-control", placeholder: "Enter website"  %>
              <label for="form_control_1">website</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_field :facebook, class: "form-control", placeholder: "Enter facebook"  %>
              <label for="form_control_1">facebook</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_field :twitter, class: "form-control", placeholder: "Enter twitter"  %>
              <label for="form_control_1">twitter</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-group form-md-line-input">
              <%= f.text_field :instagram, class: "form-control", placeholder: "Enter instagram"  %>
              <label for="form_control_1">instagram</label>
              <span class="help-block">Some help goes here...</span>
            </div>
            <div class="form-actions noborder">
              <%= f.submit 'Submit', class: "btn blue" %>
            </div>
          </div>
        <%end%>
    </div>
    <!-- END SAMPLE FORM PORTLET-->
  </div>
</div>
<!-- full width -->
<div id="full-width" class="modal container fade" tabindex="-1">
  <%= form_for @photographer, url: upd_photographers_path, method: :post, role: "form", html: {id: "modal-form", multipart: true} do |f| %>
    <% if admin_signed_in? %>
      <%= f.hidden_field :id %>
    <% end %>
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
      <h4 class="modal-title">Crop Logo</h4>
    </div>
    <div class="modal-body">
      <div id='crop-panel' hidden>
        <div id='crop-box'>
          <img id='face-canvas'>
        </div>
       <button type='button' class='btn btn-primary' id='rotate-left'>
          <span class="fa fa-rotate-left"></span>
        </button>
        <button type='button' class='btn btn-primary' id='rotate-right'>
          <span class="fa fa-rotate-right"></span>
        </button>
      </div>
        <div id="logo-input" hidden></div>
        <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h, :crop_rotate] %>
          <%= f.hidden_field attribute, :id => attribute %>
        <% end %>
    </div>
    <div class="modal-footer">
      <button type="button" data-dismiss="modal" class="btn btn-default" id='close-modal'>Close</button>
      <%= f.submit "Save changes", class: "btn blue" %>
    </div>
  <% end %>
</div>
<script>
  $(function(){
    $('#close-modal').click(function(){
      $('#big-file-input').prepend($('#logo-input').find('input'))
    })
    $('#photographer_logo').change(function(evt){
      $('#width-btn').click();
      // $clone = $(this).clone();
      $('#modal-form').find('#logo-input').append($(this))
      $('#crop-panel').show();
      var fr = new FileReader();
      fr.onload = function () {
        $('#face-canvas').attr("src", fr.result)
        $('#face-canvas').cropper({
          movable: false,
          zoomable: false,
          crop: function(e) {
            // Output the result data for cropping image.
            // console.log(e.x);
            // console.log(e.y);
            // console.log(e.width);
            // console.log(e.height);
            // console.log(e.rotate);
            $("#crop_x").val(Math.round(e.x));
            $("#crop_y").val(Math.round(e.y));
            $("#crop_w").val(Math.round(e.width));
            $("#crop_h").val(Math.round(e.height));
            $("#crop_rotate").val(Math.round(e.rotate));
          }
        })
        $('#rotate-left').click(function(){
          $('#face-canvas').cropper('rotate',-90)
        })
        $('#rotate-right').click(function(){
          $('#face-canvas').cropper('rotate',90)
        })
      }
      fr.readAsDataURL(this.files[0]);
    })
  })
</script>